include:
  - board: bmp_boost
    shield: torabo_tsuki_lp_right
    snippet: "studio-rpc-usb-uart split-central input-trackball input-listener input-trackpad-ext torabo-trackpad-live-ext input-split-listener input-split-listener-reg1 torabo-trackpad-live-split torabo-led-live torabo-caps torabo-live-feed torabo-trackball torabo-macros torabo-combos torabo-reserved-layers"
    artifact-name: torabo_tsuki_lp_right_central
  - board: bmp_boost
    shield: torabo_tsuki_lp_left
    snippet: "studio-rpc-usb-uart input-trackpad-mini input-split input-trackpad-ext-split-reg1 torabo-led-ext-periph"
    artifact-name: torabo_tsuki_lp_left_peripheral
  - board: bmp_boost
    shield: settings_reset
